please add http://tvpeer.github.io/
iptv-org/awesome-iptv pull request #112
Opened 2022-01-02 11:45 UTC by rahadiana

im create peer to peer IPTV streamming web app

- [http://tvpeer.github.io/](http://tvpeer.github.io/)

2022-01-02 12:25 UTC, freearhey requested changes

2022-01-02 12:25 UTC, freearhey commented on README.md
> +- [Peer to Peer IPTV Stream](http://tvpeer.github.io/) - Watch Peer to Peer (P2P) IPTV online from your browser.
Please specify the name of the service.

```suggestion
- [TVPeer](http://tvpeer.github.io/) - Watch Peer to Peer (P2P) IPTV online from your browser.
```

2022-01-02 19:40 UTC, rahadiana reviewed
thanks for your suggestion sir

2022-01-03 07:14 UTC, freearhey approved these changes

2022-01-03 07:14 UTC, merged