Clean up dead links and add new items
iptv-org/awesome-iptv pull request #174
Opened 2023-07-02 20:13 UTC by pintos9

2023-07-02 21:18 UTC, freearhey requested changes

2023-07-02 21:18 UTC, freearhey commented on README.md
> +- [IPTV Player Live](https://apps.apple.com/us/app/iptv-player-live-watch-tv-m3u/id1662299469) - Free IPTV player and list manager; supports M3U playlists; Picture-in-Picture playback; AirPlay and Ch
Links are sorted by date added. Please move it to the bottom of the list.

2023-07-02 21:18 UTC, freearhey commented on README.md
> +- [IPTV Player Live](https://apps.apple.com/us/app/iptv-player-live-watch-tv-m3u/id1662299469) - Free IPTV player with support for M3U playlists and Xtream Codes. Syncs your content via iCloud across
The description should fit into one sentence.

2023-07-02 22:24 UTC, pintos9 commented on README.md
> +- [IPTV Player Live](https://apps.apple.com/us/app/iptv-player-live-watch-tv-m3u/id1662299469) - Free IPTV player and list manager; supports M3U playlists; Picture-in-Picture playback; AirPlay and Ch
Got it. Done.

2023-07-02 22:29 UTC, freearhey approved these changes

2023-07-08 01:28 UTC, PopeyeTheSai10r approved these changes

2023-07-08 01:28 UTC, merged