add ebk-iptv
iptv-org/awesome-iptv pull request #234
Opened 2024-07-30 14:38 UTC by birkankervan

Ebk ip tv basic and clean ip tv interface

2024-07-31 07:43 UTC, onurakcay approved these changes

2024-08-21 20:44 UTC, freearhey requested changes

2024-08-21 20:44 UTC, freearhey commented on README.md
> +- [EBK IPTV](https://www.ebk-iptv.online/) - Watch online with pre-defined lists, add custom URLs, favorite channels/genres, channel/country search, and PWA support. High performance for web/mobile.
> the description should consist of one sentence

https://github.com/iptv-org/awesome-iptv/blob/master/.github/CONTRIBUTING.md

2024-08-21 22:23 UTC, birkankervan reviewed
fix long sentence

2024-08-21 22:35 UTC, freearhey approved these changes

2024-08-21 22:55 UTC, PopeyeTheSai10r approved these changes

2024-08-21 22:55 UTC, merged