add Threadfin (an active xTeVe fork)
iptv-org/awesome-iptv pull request #235
Opened 2024-08-04 13:38 UTC by EatPrilosec

xTeVe has a lot of errors that have been unfixed for a few years no sign of development. Threadfin has fixed some of them, uses a RAM buffer for streams, added a new UI, and some filtering and mapping features xTeVe doesn't have.

2024-08-21 20:48 UTC, freearhey requested changes

2024-08-21 20:48 UTC, freearhey commented on README.md
> +- [Threadfin](https://github.com/Threadfin/Threadfin) - M3U proxy for Kernel/Plex/Jellyfin/Emby based on xTeVe
```suggestion
- [Threadfin](https://github.com/Threadfin/Threadfin) - M3U proxy for Kernel/Plex/Jellyfin/Emby based on xTeVe.
```

2024-08-24 00:24 UTC, freearhey approved these changes

2024-08-24 12:47 UTC, PopeyeTheSai10r approved these changes

2024-08-24 12:47 UTC, merged