Update README.md
iptv-org/awesome-iptv pull request #269
Opened 2024-12-17 15:17 UTC by GodsCreation

Added Matrix Broadcasting System to the Web apps

2024-12-18 03:44 UTC, freearhey requested changes

2024-12-18 03:44 UTC, freearhey commented on README.md
> +- [Matrix Broadcasting System](http://matrixbroadcasting.com/) - A unique no downloads, no signups, no ads way of watching your favorite streams, supports local and remote m3u and m3u8 playlists
```suggestion
- [Matrix Broadcasting System](http://matrixbroadcasting.com/) - A unique no downloads, no signups, no ads way of watching your favorite streams, supports local and remote m3u and m3u8 playlists.
```

2024-12-18 18:13 UTC, freearhey approved these changes

2024-12-20 01:53 UTC, PopeyeTheSai10r approved these changes

2024-12-20 01:53 UTC, merged