Added open source KanTV player
iptv-org/awesome-iptv pull request #78
Opened 2021-06-25 05:16 UTC by zhouwg

2021-06-25 14:20 UTC, freearhey requested changes
You can also add another link to the iOS section:

```
- [kantv](https://github.com/zhouwg/kantv) - Open source player for iOS.
```

2021-06-25 14:20 UTC, freearhey commented on README.md
> +- [kantv](https://github.com/zhouwg/kantv) - Open source Android/iOS online TV/radio/movie player based on FFmpeg n4.4, derived from original ijkplayer(https://github.com/bilibili/ijkplayer) , with s
```suggestion
- [kantv](https://github.com/zhouwg/kantv) - Open source player for Android.
```

2021-06-25 15:33 UTC, zhouwg commented
> - [kantv](https://github.com/zhouwg/kantv) - Open source player for iOS

thanks your comment.

focus on target Android and very limited supportive for target iOS in project kantv at the moment. should I add another link to iOS section?

2021-06-25 16:01 UTC, freearhey approved these changes

2021-06-25 16:01 UTC, freearhey commented
No, you don't have to.

2021-06-25 16:01 UTC, merged

2021-06-26 01:39 UTC, zhouwg reviewed
> No, you don't have to.

thanks.

2021-06-26 01:39 UTC, zhouwg commented on README.md
> +- [kantv](https://github.com/zhouwg/kantv) - Open source Android/iOS online TV/radio/movie player based on FFmpeg n4.4, derived from original ijkplayer(https://github.com/bilibili/ijkplayer) , with s
thanks your comment. I had been updated the PR accordingly.